### ISSUE TITLE
Impossible to generate CLDF

### ISSUE THREAD

**Issue by tresoldi** [lexibank/allenbai#5]
It is currently impossible to generate the CLDF files, as the `Allen-2005-500` conceptlist in Concepticon has different concept numbers for `TWIST (ROPE)` (it has 272, while the source data and Concepticon itself has 430; 272 in Concepticon is `TONGS`). The bug was introduced as part of the reorganization of Concepticon back in August.

**Comment by xrotwang** [comment]
Uh, good find! Usage is the best that can happen to data :)

**Comment by tresoldi** [comment]
Pinging @schweikhard

**Comment by LinguList** [comment]
Okay, as just said: we are allowed to make manual overrides, if we encounter that a concept list is not perfectly reflecting the data. We had that a lot in the past, and there's no reason to not do it. Especially since in many cases the concept list published may indeed be different from the data published (we have examples for that).

**Comment by tresoldi** [comment]
Made the PR, we can close the issue when approved.
